Add `rs.utils.polar_axes()` for classifying which cell axes permit continuous origin shifts
Hekstra-Lab/reciprocalspaceship pull request #177
Opened 2022-08-25 17:03 UTC by JBGreisman

Based on the routine implemented in `is_polar()`, it's also possible to return which of the cell axes in a given spacegroup are polar (permit continuous origin shifts). This is implemented here as `rs.utils.polar_axes()` with the following call signature:

`polar_axes(spacegroup) --> List(3) of bools`

For example:
```python 
import reciprocalspaceship as rs
print(rs.utils.polar_axes("P 1"))         # [True, True, True]
print(rs.utils.polar_axes("P 1 21 1"))    # [False, True, False]
print(rs.utils.polar_axes("P 21 21 21"))  # [False, False, False]
```

One implementation decision was to only support hexagonal Bravais lattices for the relevant "R 3" trigonal space groups. This decision is made so that it is clear that the function returns polar axes corresponding to the a, b, and c-axes, and not the a', b', c' corresponding to the rhombohedral setting. The supported hexagonal case is the reference setting for these spacegroups, so I think this is a reasonable design choice. To avoid confusion, a ValueError is raised when such space groups are given with a rhombohedral setting. 

The code is tested against all applicable spacegroup settings in `sgtbx` using the `is_allowed_origin_shift()` method.

2022-08-25 18:22 UTC, kmdalton requested changes
Just a small nitpick. About a docstring.

2022-08-25 18:22 UTC, kmdalton commented on reciprocalspaceship/utils/symmetry.py
> +        List of whether a-, b-, or c-axis is polar
make clear this is a list of booleans.

2022-08-25 19:06 UTC, JBGreisman commented on reciprocalspaceship/utils/symmetry.py
> +        List of whether a-, b-, or c-axis is polar
makes sense -- updated in latest commit

2022-08-26 20:07 UTC, kmdalton approved these changes
You have resolved my issues. Looks good!

2022-08-27 14:01 UTC, merged